version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  myapp:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
